steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '.']

 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'us-central1-docker.pkg.dev/niveus-gcp-training-4/karthik-node-app/my-node-js-app:latest']
