options:
  logging: CLOUD_LOGGING_ONLY

steps:

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'node-js-app', '.']


- name: 'gcr.io/cloud-builders/docker'
  args: ['images']


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/niveus-gcp-training-4/karthik-node-app/my-node-js-app:latest']

